### ISSUE TITLE
Support Kerberos authentication with service discovery

### ISSUE THREAD

**Issue by beauremus** [fermi-ad/acsys-python#16]
Support Kerberos authentication with service discovery. For a smooth rollout, this requires two authentication strategies in the client until we can deprecate the old version.

The existing clients are latched to `DPM01` by default. We can deploy a new incremental update that has the principal hardcoded for DPM01 and supports the new message type that tells the client what principal to use.

**Comment by rneswold** [comment]
So the plan is
* Do service discovery to pick a DPM
* When Kerberos is needed, start the exchange
* If `Authenticate_reply` is received, continue successfully. Otherwise, if `Status_reply` is received, switch over to DPM01 and hardcode the service name.

**Comment by rneswold** [comment]
Done: b8390026c96b6ecc4c6dad897808e9e5c35c557a

When switching from a DPM that doesn't do the proper Kerberos exchange, the runtime emit a message saying a `GeneratorExit` exception wasn't getting handled. I cannot figure out why it's reporting this. If anyone wants to try to figure it out, I'd appreciate it. It doesn't affect the script from running.

**Comment by rneswold** [comment]
Once all DPMs use the new Kerberos protocol, the code in this commit can be simplified.

**Comment by rneswold** [comment]
The "old" protocol is no longer used.
