### ISSUE TITLE
Finish documentation move to GitHub.

### ISSUE THREAD

**Issue by rneswold** [fermi-ad/acsys-python#22]
@beauremus already moved our documentation here (thanks, Beau!) We should remove the documentation on Redmine so the two sites don't get out-of-sync and put a link on our "Python Environment" page to point to these docs.

**Comment by beauremus** [comment]
To be clear, I moved **some** of our documentation here. Enough to point Kyle to data sources information.

**Comment by rneswold** [comment]
Okay:

- [x] Make sure the GitHub Wiki has *all* the latest documentation
- [x] Remove it from Redmine and add a link on our main page to point here.

**Comment by rneswold** [comment]
I transferred the handful of pages and did a quick translate into GitHub's markdown. I also edited the main page on Redmine to point to this documentation.
