### ISSUE TITLE
Support ramp card settings

### ISSUE THREAD

**Issue by beauremus** [fermi-ad/acsys-python#23]
Ramp cards don't follow standard conventions. We need to develop methods for setting `f(t)` and `dt` values for CAMAC 400 family cards.

Edit: Correct `d(t)` to `dt`

**Comment by beauremus** [comment]
Jeff Eldred only needs support to set `f(t)` values. `dt` is more complex and should be evaluated further before implementing.

**Comment by rneswold** [comment]
Ramp card devices, where the last byte of the SSDN is `Fx`, are "knobbable". These devices are designed to adjust multiple `f(t)` values without changing their `dt` values. It allows an operator to "knob" the flattop of a ramp. Maybe Jeff could take advantage of that device?

(I agree that there should be a general API for interacting with ramp cards, though.)

**Comment by rneswold** [comment]
Added support (35f33659e546f31efcddfc4d22bda05dd723562b) for a scaling service (@charlieking65 implemented the service in Java.) We can support Jeff's need using this service and an additional function.

There is a minor issue in that he gets a `StopAsyncIteration` exception when he uses the additional function. In other, similar cases we needed to add a `try-except` block which catches and ignores the error. It would be nice to do this in the library so Jeff (and future users) wouldn't have to in their code.

**Comment by rneswold** [comment]
Maybe this line: https://github.com/fermi-controls/acsys-python/blob/35f33659e546f31efcddfc4d22bda05dd723562b/acsys/dpm/__init__.py#L815 is where the `StopAsyncIteration` is escaping.

**Comment by rneswold** [comment]
Maybe this: https://github.com/fermi-controls/acsys-python/blob/35f33659e546f31efcddfc4d22bda05dd723562b/acsys/dpm/__init__.py#L317 should be
```python
    return None
```
so it closes out the generator.

**Comment by rneswold** [comment]
Jeff verified it's working. The exception warning is being tracked by another issue.
