### ISSUE TITLE
More featureful data type checking

### ISSUE THREAD

**Issue by beauremus** [fermi-ad/acsys-python#25]
`.isReadingFor(0)` is a convenient method for checking that a response is for a particular `tag`.

What if I want to run the same method for multiple `tag`s?

I propose that `.isReadingFor` take n arguments that allow for as many `tag`s as the developer wants.

Also, if the same code is run no matter the tag `.isReadingFor` should accept zero arguments allowing for the type to be checked without consideration for the `tag`.

**Comment by rneswold** [comment]
So you're proposing something like:

```python
def isReadingFor(self, *tags):
    return self.tag in tags

def isStatusFor(self, *tags):
    return self.tag in tags
```

(and eventually making it snake-case 😄)

EDIT: I offer this up because I'm trying to get used to Python's function argument passing options. I don't know if this will work.

**Comment by beauremus** [comment]
Your example will work for allowing something like `.isReadingFor(2,3,4)`. 🎉

**Comment by beauremus** [comment]
If we want to accept `.isReadingFor([1,2,3])` then we need to flatten the input. I believe that could be done with

```python
import itertools
def isReadingFor(self, *tags):
    return self.tag in itertools.chain(tags)
```

**Comment by rneswold** [comment]
I *don't* want to pass an array. I like the earlier example. 👍🏻
