### ISSUE TITLE
Generate RPM for deployment

### ISSUE THREAD

**Issue by beauremus** [fermi-ad/acsys-python#26]
Instrumentation requests that this library be installable via yum rpm.

**Comment by rneswold** [comment]
Wouldn't `pip` or `poetry` install it in a more Pythonic way? If we create the `.rpm`, are we going to have to include stuff to make it recognized by the local Python installation?

**Comment by beauremus** [comment]
It appears we can simply build for the rpm target. Since it uses the same process we do for building the tarball, I assume it will unpack in the same way. Maybe that's a bad assumption?

https://docs.python.org/3/distutils/builtdist.html#creating-rpm-packages

**Comment by rneswold** [comment]
The `acsys` tarball contains things like an `acsys.egg-info` subdirectory. I don't know if `pip` has a registry or if it simply scans the directory in `PYTHONPATH` to see what's installed.

Would `rpm` users know where to unpack the tarball? Would they be able to `rpm`-install any dependencies?

Can we pull Bobby S. into this?

**Comment by beauremus** [comment]
I misunderstood this request. It has to do with `acnetd` and the `ACSys-Erlang` environment.
