### ISSUE TITLE
`async` generator ignoring `AsyncStopIteration` exception.

### ISSUE THREAD

**Issue by rneswold** [fermi-ad/acsys-python#27]
In early versions of this package, @beauremus and I found and fixed several instances where exiting from the `async for` loop early would print this warning message because the generator wasn't getting cleaned up properly. While working on #23, I found that `DPM.replies()` was also generating these messages.

I attempted to fix it with 610e297e4f495d3aab475006aaed2464f4131a40. I opened this issue to document and track fixing that bug.

**Comment by beauremus** [comment]
82da467c6976607ee6f8df6b90ffae6d4c71de6b closes this issue.
