### ISSUE TITLE
Allow arguments to be passed in `acsys.run_client()`

### ISSUE THREAD

**Issue by rneswold** [fermi-ad/acsys-python#4]
@kjhazelwood: It would be nice if the `run_client` function would have an arguments field where the user could pass arguments to the target async method in addition to the newly create connection object.

**Comment by rneswold** [comment]
@kjhazelwood : Are you looking for `**kwargs` style? So a `main` function would look like this:

```python
async main(con, **args):
    # do stuff
```

and you would invoke it as:

```python
acsys.run_client(main, arg1='first', arg2='second')
```

Or the `*args` style?

**Comment by kjhazelwood** [comment]
I dont think I have a preference, which ever is most convenient to implement.

**Comment by rneswold** [comment]
Done: d288cfa95602b48f81012105b64fea62d9b021dc

This allows keyword arguments to be passed (they seemed the most flexible.) The next release will contain this feature.
